theme = "showfolio"
languageCode = "en-us"
baseurl = "https://raulsanchezzt.com"
title = "RaÃºl SÃ¡nchez"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[params]
  name = "RaÃºl SÃ¡nchez's portfolio"
  description = "My personal portfolio."
  author = "RaÃºl SÃ¡nchez"
  authorEmail = "raulsanchezzt@duck.com"
  authorImage = "/photo.png"
  autoDarkMode = true
  copyright = "Copyright Â© 2022 - RaÃºl SÃ¡nchez Â· All rights reserved"
  favicon = "/favicon.png"

[params.homepage]
  title = "Hey ğŸ‘‹ I am RaÃºl"
  tagline = "`If you don't fail, you're not even trying.Â´"
  description = "I am a student of vocational training of network computer systems administrator."
  contact = "mailto:raulsanchezzt@duck.com"

[[params.homepage.projects]]
  url = "https://raulsanchezzt.gitbook.io/hack-the-box/"
  title = "ğŸ“¦ï¸ Hack The Box"
  subtitle = "Blog, Cybersecurity"
  description = "My personal blog where I write about how I compromise Hack The Box machines in detail."

[[params.homepage.projects]]
  url = "https://github.com/RaulSanchezzt/kali-bspmw"
  title = "ğŸ–¥ï¸ Kali-bspwm"
  subtitle = "Linux, Window Manager"
  description = "Script written in bash to configure the desktop environment with the bspwm tiling window manager automatically. Also other tools like polybar, rofi, kitty terminal and neovim are installed."

[[params.homepage.projects]]
  url = "https://github.com/RaulSanchezzt/"
  title = "ğŸ’¾ Other projects"
  subtitle = "Github"
  description = "You can find all the other projects I made on Github!"

[params.homepage.resume]
  skills = [ 
  "Bash, Python, SQL, Git, Docker.",
  "Networks and Operating Systems.",
  "Use of Linux, Virtualization and Data Bases.",  
  "Agile development and team work."
  ]

[[params.homepage.resume.work]]
   name = "Ecomputer"
   role = "Assembly and Maintenance of Computers"
   duration = "March 2021 - June 2021"

[[params.homepage.resume.courses]]
  name = "Higher Technician in Computer Network Systems Management"
  provider = "Integrated Polytechnic Centre ETI"
  duration = "September 2021 - Present"

[[params.homepage.resume.courses]]
  name = "Technician in Microcomputer Systems and Networks"
  provider = "Integrated Polytechnic Centre ETI"
  duration = "September 2019 - March 2021"

[params.homepage.social]
  twitter = "https://twitter.com/RaulSanchezzt"
  linkedin = "https://www.linkedin.com/in/RaulSanchezzt"
  github = "https://github.com/RaulSanchezzt"
  email = "mailto:raulsanchezzt@duck.com"

[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"

[languages]
  [languages.en]
    title = "RaÃºl SÃ¡nchez"
    languageName = "ğŸ‡ºğŸ‡¸ EN"
    weight = 1
  [languages.es]
    title = "RaÃºl SÃ¡nchez"
    languageName = "ğŸ‡ªğŸ‡¸ ES"
    weight = 2
      
      [languages.es.params.homepage]
        title = "Hola! ğŸ‘‹ Soy RaÃºl"
        tagline = "`Si no fallas, ni siquiera lo estÃ¡s intentando.Â´"
        description = "Soy un estudiante de grado superior sobre AdministraciÃ³n de Sistemas InformÃ¡ticos en Red."
        contact = "mailto:raulsanchezzt@duck.com"
        
      [[languages.es.params.homepage.projects]]
        url = "https://raulsanchezzt.gitbook.io/hack-the-box/"
        title = "ğŸ“¦ï¸ Hack The Box"
        subtitle = "Blog, Ciberseguridad"
        description = "Mi blog personal donde escribo sobre como comprometo las mÃ¡quinas de Hack The Box machines en detalle."

      [[languages.es.params.homepage.projects]]
        url = "https://github.com/RaulSanchezzt/kali-bspmw"
        title = "ğŸ–¥ï¸ Kali-bspwm"
        subtitle = "Linux, Gestor de Ventanas"
        description = "Script escrito en bash para configurar el entorno de escritorio con un gestor de ventanas en mosaico como bspwm automÃ¡ticamente. AdemÃ¡s se instalan otras herramientas como polybar, rofi, kitty terminal y neovim."

      [[languages.es.params.homepage.projects]]
        url = "https://github.com/RaulSanchezzt/"
        title = "ğŸ’¾ Otros proyectos"
        subtitle = "Github"
        description = "Puedes encontrar todos los demÃ¡s proyectos que he hecho en Github!"

      [languages.es.params.homepage.resume]
        skills = [ 
        "Bash, Python, SQL, Git, Docker.",
        "Redes y Sistemas Operativos.",
        "Uso de Linux, Virtualizacion y Bases de Datos.",  
        "Desarrollo Ã¡gil y trabajo en equipo."
        ]

      [[languages.es.params.homepage.resume.work]]
        name = "Ecomputer"
        role = "Montaje y Mantenimiento de Ordenadores"
        duration = "Marzo 2021 - Junio 2021"

      [[languages.es.params.homepage.resume.courses]]
        name = "TÃ©cnico Superior en AdministraciÃ³n de Sistemas InformÃ¡ticos en Red"
        provider = "Centro Integrado PolitÃ©cnico ETI"
        duration = "Septiembre 2021 - Presente"

      [[languages.es.params.homepage.resume.courses]]
        name = "TÃ©cnico en Sistemas MicroinformÃ¡ticos y Redes"
        provider = "Centro Integrado PolitÃ©cnico ETI"
        duration = "Septiembre 2019 - Marzo 2021"

      [languages.es.params.homepage.social]
        twitter = "https://twitter.com/RaulSanchezzt"
        linkedin = "https://www.linkedin.com/in/RaulSanchezzt"
        github = "https://github.com/RaulSanchezzt"
        email = "mailto:raulsanchezzt@duck.com"
